apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-firefox-rep
spec:  
  replicas: 2
  selector:
    app: selenium-node-firefox
  template:
    metadata:
      name: selenium-node-firefox
      labels:
        app: selenium-node-firefox
    spec:
      containers:
        - name: selenium-node-firefox
          image: seleniarm/node-firefox:4.0.0-beta-1-20210215
          ports:
            - containerPort: 5901
          env:
           - name:  HUB_HOST
             value: "selenium-srv" 
           - name: HUB_PORT
             value: "4444"
           - name : SE_EVENT_BUS_HOST
             value: "selenium-hub-demo"
           - name : SE_EVENT_BUS_PUBLISH_PORT
             value: "4442"
           - name : SE_EVENT_BUS_SUBSCRIBE_PORT
             value: "4443"  